import { Person } from '@users/domain/entities/person.entity';
import { User } from '@users/domain/entities/user.entity';
import { LoanInstallment } from './loan-installment.entity';

export class Loan {
  id?: string; // Optional because it is auto-generated by DB
  idPeople: number;
  startDate: Date;
  endDate: Date;
  amount: number;
  interest: number;
  fee: number;
  days: number;
  createdAt: Date;
  userId: number;
  status: string;
  address: string;
  phone: string;
  paidToday?: number;
  remainingAmount?: number;
  inIntervalPayment?: number;
  person?: Person;
  user?: User;
  installments?: LoanInstallment[];

  constructor(
    idPeople: number,
    startDate: Date,
    endDate: Date,
    amount: number,
    interest: number,
    fee: number,
    days: number,
    createdAt: Date,
    userId: number,
    status: string,
    address: string,
    phone: string,
    id?: string,
  ) {
    this.id = id;
    this.idPeople = idPeople;
    this.startDate = startDate;
    this.endDate = endDate;
    this.amount = amount;
    this.interest = interest;
    this.fee = fee;
    this.days = days;
    this.createdAt = createdAt;
    this.userId = userId;
    this.status = status;
    this.address = address;
    this.phone = phone;
  }

  /**
   * Valida si el préstamo puede recibir un pago en la fecha indicada.
   * Regla: La fecha de pago debe ser mayor o igual a la fecha de inicio del préstamo.
   */
  canAcceptPayment(paymentDate: Date): boolean {
    const start = new Date(this.startDate);
    start.setHours(0, 0, 0, 0);

    const target = new Date(paymentDate);
    target.setHours(0, 0, 0, 0);

    return target >= start;
  }
}
