export class Loan {
    id?: string; // Optional because it is auto-generated by DB
    idPeople: number;
    startDate: Date;
    endDate: Date;
    amount: number;
    interest: number;
    fee: number;
    createdAt: Date;
    userId: number;
    status: string;

    constructor(
        idPeople: number,
        startDate: Date,
        endDate: Date,
        amount: number,
        interest: number,
        fee: number,
        createdAt: Date,
        userId: number,
        status: string,
        id?: string,
    ) {
        this.id = id;
        this.idPeople = idPeople;
        this.startDate = startDate;
        this.endDate = endDate;
        this.amount = amount;
        this.interest = interest;
        this.fee = fee;
        this.createdAt = createdAt;
        this.userId = userId;
        this.status = status;
    }
}
