export class Company {
  id?: string; // Auto-generated by database
  companyName: string;
  status: string;
  createdAt: Date;

  label?: string;
  subdomain?: string;

  constructor(
    companyName: string,
    status: string,
    createdAt: Date,
    id?: string,
    label?: string,
    subdomain?: string,
  ) {
    this.id = id;
    this.companyName = companyName;
    this.status = status;
    this.createdAt = createdAt;
    this.label = label;
    this.subdomain = subdomain;
  }

  getNormalizedStatus(): string {
    const rawStatus = this.status;
    if (rawStatus === 'ACTIVO') return 'ACTIVE';
    if (rawStatus === 'INACTIVO') return 'INACTIVE';
    if (rawStatus === 'SUSPENDIDO') return 'SUSPENDED';
    return rawStatus;
  }
}
