import { IsNotEmpty, IsString, IsOptional } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class LoginDto {
  @ApiProperty({ example: 'admin', description: 'Username' })
  @IsString()
  @IsNotEmpty()
  username: string;

  @ApiProperty({
    example: 'mySecurePassword',
    description: 'Plain text password',
  })
  @IsString()
  @IsNotEmpty()
  password: string;

  @ApiProperty({
    example: '550e8400-e29b-41d4-a716-446655440000',
    description: 'Unique client fingerprint (UUID generated by client)',
  })
  @IsString()
  @IsNotEmpty()
  fingerprint: string;

  @ApiProperty({
    example: 'empresa1',
    description: 'Tenant or Subdomain',
    required: false,
  })
  @IsString()
  @IsOptional()
  tenant?: string;
}
